config_list = {
    "sprites": {
        "data_path": "./Data/sprites.h5",
        "batch_size": 6,
        "batch_size_val": 4,
        "val_split": 0.1,
        "list_dim": 3,
        "sigma": 0.02,
        "data_smooth": 2.8,
        "seg_size": 28,
        "seg_shift": 4,
        "no_ground": False,
        "transformSpace": True,
        "data_path_test": "./Data/sprites_test.h5",
        "k_test": 10,
    },
    "mnist": {
        "data_path": "./Data/mnist.h5",
        "batch_size": 6,
        "batch_size_val": 4,
        "val_split": 0.1,
        "list_dim": 16,
        "sigma": 0.02,
        "data_smooth": 2.8,
        "seg_size": 28,
        "seg_shift": 4,
        "no_ground": False,
        "data_path_test": "./Data/mnist_test.h5",
        "transformSpace": True,
        "k_test": 10,
    },
    "cells": {
        "data_path": "./Data/cells.h5",
        "batch_size": 6,
        "batch_size_val": 4,
        "val_split": 0.1,
        "list_dim": 2,
        "sigma": 0.02,
        "data_smooth": 4.8,
        "seg_size": 48,
        "seg_shift": 6,
        "no_ground": True,
        "data_path_test": "./Data/cells_test.h5",
        "transformSpace": True,
        "k_test": 10,
	    "g_n_pad": 0
    },
    "tetris": {
        "data_path": "./Data/tetris.h5",
        "batch_size": 40,
        "batch_size_val": 40,
        "val_split": 0.1,
        "list_dim": 8,
        "sigma": 0.02,
        "data_smooth": 2,
        "seg_size": 20,
        "seg_shift": 3,
        "memory_size": 2,
        "no_ground": False,
        "transformSpace": True,
        "data_path_test": "./Data/tetris_test.h5",
        "k_test": 3,
    }
}
